---
- name: Provision & Configure Database Server (MySQL)
  hosts: database-server
  remote_user: root
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3.10
  tasks:
    - include_vars:
        file: ../vars.yml
    - include_role:
        name: ./roles/database-server
